# colors 
set -g default-terminal "tmux-256color" 

# change prefix to Ctrl+A
unbind C-b
set -g prefix C-a

# shorter delay for Esc
set -s escape-time 100

# start windows and panes at index 1
set -g base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

# tab titles
set-option -g set-titles on
set-option -g set-titles-string "[BuildTmux]  #{session_name} : #{window_name}"

# better shortcuts for splitting windows
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

# pane navigation
# - jump to pane with Ctrl
# - resize with Shift
bind  C-Left  select-pane -L
bind  C-Down  select-pane -D
bind  C-Up    select-pane -U
bind  C-Right select-pane -R
bind  -r S-Left  resize-pane -L
bind  -r S-Down  resize-pane -D
bind  -r S-Up    resize-pane -U
bind  -r S-Right resize-pane -R
# window navigation
bind Left previous-window
bind Right next-window

# move windows
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# resize
setw -g aggressive-resize on

# join a pane to a window
#bind j choose-window 'join-pane -h -s "%%"'
#bind J choose-window 'join-pane -s "%%"'

# new window and retain cwd
bind c new-window -c "#{pane_current_path}"

# history
set -g history-limit 50000

# mouse mode
set -g mouse on

# reload config
bind-key r source-file ~/.tmux.conf \; display-message "Tmux config reloaded!"
bind C-e new-window -n 'tmux.conf' "sh -c '\${EDITOR:-vim} ~/.tmux.conf && tmux source-file ~/.tmux.conf && tmux display-message \"Tmux config reloaded!\"'"

# theme
%if "#{==:#{host},toolbx}"
    %hidden CONFNAME=$BOXNAME
%else
    %hidden CONFNAME=$HOSTNAME
%endif
source-file ~/.tmux/neokyoto-$CONFNAME.colors
source-file ~/.tmux/neokyoto.theme


# List of plugins
set -g @plugin 'tmux-plugins/tpm'

#set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# continuum doesn't work when more than one tmux server is running
# to enable it for a particular machine, create an option file.
if-shell "[ -f ~/.tmux/options-$CONFNAME.tmux ]" "source-file ~/.tmux/options-$CONFNAME.tmux"

# resurrect
set -g @resurrect-capture-pane-contents 'on'

# better-mouse-mode
set -g @scroll-without-changing-pane on
set -g @emulate-scroll-for-no-mouse-alternate-buffer on

# yank
set -g @custom_copy_command 'xsel -b -i'
set -g @yank_selection 'clipboard'       # 'primary', 'secondary' or 'clipboard'
set -g @yank_selection_mouse 'clipboard' # 'primary', 'secondary' or 'clipboard'
set -g @yank_action 'copy-pipe'          # 'copy-pipe-and-cancel' (default) or 'copy-pipe'

## gitmux - install binary from https://github.com/arl/gitmux

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
