# in comments, [K]keyname refers to the physical keyboard keys.

[ids]

0001:0001

[global]
oneshot_timeout = 2500

[main]

# [K]capslock and [K]altgr are the EXTEND layer.
capslock = overloadt2(extend, tab, 200)
altgr = overloadt2(extend, oneshot(altgr), 200)

# [K]alt and [K]enter are the NAV layer
alt = overloadt2(nav, oneshot(nav), 200)
enter = overloadt2(nav, enter, 200)

# [K]Space also acts as Shift when held
space = overloadi(space, overloadt2(shift, space, 200), 150)

# [K]rightcontrol is the MODE layer
rightcontrol = overloadt2(mode, oneshot(mode), 200)

# Homerow mods
a = overloadi(a, overloadt2(meta,    a, 200), 150)
s = overloadi(s, overloadt2(alt,     s, 200), 150)
d = overloadi(d, overloadt2(shift,   d, 200), 150)
f = overloadi(f, overloadt2(control, f, 200), 150)

j = overloadi(j, overloadt2(control, j, 200), 150)
k = overloadi(k, overloadt2(shift,   k, 200), 150)
l = overloadi(l, overloadt2(alt,     l, 200), 150)
; = overloadi(;, overloadt2(meta,    ;, 200), 150)

tab = esc
leftmeta = layer(alt)
sysrq = layer(meta)

# [K]Fn only works as a slow tap
wakeup = layer(meta)

# Show layout
]+\ = macro(sport)

# combos
z+x = C-z
x+c = C-c
c+v = C-v
v+b = C-y
x+v = C-x
w+e = C-s
u+i = C-backspace
i+o = backspace
e+d = esc
r+f = macro(esc :)
u+j = -
j+m = S--
i+k = '
o+l = S-'
l+. = \
f+v = :
d+c = ;
a+z = macro(q u)

# =================================================
#     E X T E N D
# =================================================
[extend]

# restore keys on this layer
space = space
enter = enter
tab = tab

# sticky modifiers in GASC order
a = overloadt2(meta, oneshot(meta), 200)
s = overloadt2(alt, oneshot(alt), 200)
d = overloadt2(shift, oneshot(shift), 200)
f = overloadt2(control, oneshot(control), 200)

# cursor movement
j = left
l = right
i = up
k = down
u = pageup
o = pagedown
y = home
h = end

; = backspace
. = C-backspace
/ = delete

n = S-tab
m = tab
' = `

w = C-w
e = C-f
t = insert

# undo, cut, copy, paste, redo
z = C-z
x = C-x
c = C-c
v = C-v
b = C-y
 
# Gnome window control - F17
p = f17

# =================================================
#     N A V
# =================================================
[nav]

# restore keys on this layer
capslock = capslock
space = space
enter = enter
tab = tab

# desktop navigation
j = M-f1
k = M-f2
l = M-f3
; = M-f4
# tab navigation
u = A-1
i = A-2
o = A-3
p = A-4
# tab nav, context menu
h = C-pageup
n = C-pagedown
, = C-A-pageup
. = C-A-pagedown
' = compose
# terminal copy / paste
c = C-S-c
v = C-S-v
# application shortcuts
q = C-M-o
w = C-M-w
e = C-M-f
r = C-M-l
a = C-M-a
d = C-M-s
f = C-M-b
g = C-S-M-t
v = C-M-t
z = C-M-x
# media playback
\ = playpause
[ = C-S-M-[
] = C-S-M-]

# search (in current fil)
. = f3
/ = S-f3

[nav+shift]
#search with Shift (across files)
. = f8
/ = C-f8

# =================================================
#     M O D E
# =================================================
[mode]

a = x
altgr = layer(altgr)
sysrq = rightcontrol

# layout switch
1 = setlayout(main)
2 = setlayout(colemak)

# =================================================
#     C O L E M A K    L A Y E R
# =================================================
[colemak:layout]

# Homerow mods
a = overloadi(a, overloadt2(meta,    a, 200), 150)
s = overloadi(r, overloadt2(alt,     r, 200), 150)
d = overloadi(s, overloadt2(shift,   s, 200), 150)
f = overloadi(t, overloadt2(control, t, 200), 150)

j = overloadi(n, overloadt2(control, n, 200), 150)
k = overloadi(e, overloadt2(shift,   e, 200), 150)
l = overloadi(i, overloadt2(alt,     i, 200), 150)
; = overloadi(o, overloadt2(meta,    o, 200), 150)

q = q
w = w
e = f
r = p
t = b
y = j
u = l
i = u
o = y
p = ;
#a = a
#s = r
#d = s
#f = t
g = g
h = m
#j = n
#k = e
#l = i
#; = o
z = x
x = c
c = d
v = v
b = z
n = k
m = h

